const TEAM_EMOJI = {
  'Akron Zips': '🦘',
  'Alabama Crimson Tide': '🌊',
  'Arizona Wildcats': '🐱',
  'Arkansas Razorbacks': '🐗',
  'BYU Cougars': '🐆',
  'California Baptist Lancers': '⚔️',
  'Clemson Tigers': '🐯',
  'Duke Blue Devils': '😈',
  'Florida Gators': '🐊',
  'Furman Paladins': '🛡️',
  'Georgia Bulldogs': '🐶',
  'Gonzaga Bulldogs': '🐶',
  "Hawai'i Rainbow Warriors": '🌈',
  'High Point Panthers': '🐾',
  'Hofstra Pride': '🦁',
  'Houston Cougars': '🐆',
  'Idaho Vandals': '⚡',
  'Illinois Fighting Illini': '🪃',
  'Iowa Hawkeyes': '🦅',
  'Iowa State Cyclones': '🌪️',
  'Kansas Jayhawks': '🦅',
  'Kennesaw State Owls': '🦉',
  'Kentucky Wildcats': '🐱',
  'Lehigh Mountain Hawks': '🦅',
  'Long Island University Sharks': '🦈',
  'Louisville Cardinals': '🐦',
  'McNeese Cowboys': '🤠',
  'Miami (OH) RedHawks': '🦅',
  'Miami Hurricanes': '🌀',
  'Michigan State Spartans': '⚔️',
  'Michigan Wolverines': '🦡',
  'Missouri Tigers': '🐯',
  'NC State': '🐺',
  'Nebraska Cornhuskers': '🌽',
  'North Carolina Tar Heels': '👟',
  'North Dakota State Bison': '🦬',
  'Northern Iowa Panthers': '🐾',
  'Ohio State Buckeyes': '🌰',
  'Pennsylvania Quakers': '🎩',
  'Prairie View A&M Panthers': '🐾',
  'Purdue Boilermakers': '🔨',
  'Queens University Royals': '👑',
  'SMU Mustangs': '🐴',
  'Saint Louis Billikens': '🎭',
  "Saint Mary's Gaels": '☘️',
  'Santa Clara Broncos': '🐴',
  'Siena Saints': '✝️',
  'South Florida Bulls': '🐂',
  "St. John's Red Storm": '⛈️',
  'TCU Horned Frogs': '🐸',
  'Tennessee State Tigers': '🐯',
  'Tennessee Volunteers': '🍊',
  'Texas': '🤘',
  'Texas A&M Aggies': '🐕',
  'Texas Tech Red Raiders': '⚔️',
  'Troy Trojans': '🏛️',
  'UCF Knights': '⚔️',
  'UCLA Bruins': '🐻',
  'UConn Huskies': '🐕',
  'Utah State Aggies': '🐕',
  'VCU Rams': '🐏',
  'Vanderbilt Commodores': '⚓',
  'Villanova Wildcats': '🐱',
  'Virginia Cavaliers': '⚔️',
  'Wisconsin Badgers': '🦡',
  'Wright State Raiders': '✈️',
};

export function teamEmoji(teamName) {
  if (!teamName) return '';
  return TEAM_EMOJI[teamName] || '';
}
